skills = [
        "python",
        "sql",
        "c++",
        "java",
        "git",
        "machine learning",
        "data analysis",
        "deep learning",
        "tensorflow",
        "c#",
        "javascript",
        "html",
        "css",
        "react",
        "angular",
        "node.js",
        "django",
        "flask",
        "spring",
        "ruby",
        "php",
        "swift",
        "kotlin",
        "go",
        "matlab",
        "scala",
        "aws"
    ]